### ISSUE TITLE
Deserialization of complex this.state in Stores

### ISSUE THREAD

**Issue by jareware** [goatslacker/alt#413] opened 2015-07-23 07:02 UTC
I use an Immutable Map as my Store state, [as in here](https://github.com/goatslacker/alt/blob/1a7fe7371dbc956684bb8e38728d84c7b165327a/test/immutable-stores.js#L11).

However, with that type of Store, I'm not able to deserialize properly, and it looks like [these lines](https://github.com/goatslacker/alt/blob/021fbc648fab8986ff35bc128095b4a1a54e61c3/src/alt/utils/StateFunctions.js#L11-12) should use `setState()` if one is available in config instead of directly assuming it's an object..?

**Comment by jdlehman** [comment] 2015-07-23 12:37
I am closing this because it is a duplicate of #366 so we can keep discussion in a single place.

**Closed by jdlehman** 2015-07-23 12:37 UTC

**Comment by jareware** [comment] 2015-07-23 14:07
Sorry, didn't spot that!
